version: "3"
services:
    phpfpmuploadlabs:
        image: php:5.6-fpm-alpine
        restart: always
        volumes:
            - ./www:/www/wwwroot/upload

    nginxuploadlabs:
        image: nginx:1.20-alpine
        volumes:
            - ./nginx:/etc/nginx/templates
            - ./www:/www/wwwroot/upload
        ports:
            - "8080:80"
        environment:
            HOST: localhost
            PORT: 80
            WEB_ROOT: /www/wwwroot/upload/
            PHP_FPM: phpfpm_upload_labs:9000
